<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            [
                'name' => 'Bangladesh',
                'iso2' => 'BD',
                'iso3' => 'BGD',
                'phone_code' => '+880',
                'currency_code' => 'BDT',
                'currency_name' => 'Bangladeshi Taka',
                'capital' => 'Dhaka',
                'region' => 'Asia',
                'subregion' => 'Southern Asia',
            ],
            [
                'name' => 'Afghanistan',
                'iso2' => 'AF',
                'iso3' => 'AFG',
                'phone_code' => '+93',
                'currency_code' => 'AFN',
                'currency_name' => 'Afghan Afghani',
                'capital' => 'Kabul',
                'region' => 'Asia',
                'subregion' => 'Southern Asia',
            ],
            [
                'name' => 'Albania',
                'iso2' => 'AL',
                'iso3' => 'ALB',
                'phone_code' => '+355',
                'currency_code' => 'ALL',
                'currency_name' => 'Albanian Lek',
                'capital' => 'Tirana',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
            ],
            [
                'name' => 'Algeria',
                'iso2' => 'DZ',
                'iso3' => 'DZA',
                'phone_code' => '+213',
                'currency_code' => 'DZD',
                'currency_name' => 'Algerian Dinar',
                'capital' => 'Algiers',
                'region' => 'Africa',
                'subregion' => 'Northern Africa',
            ],
            [
                'name' => 'Andorra',
                'iso2' => 'AD',
                'iso3' => 'AND',
                'phone_code' => '+376',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'capital' => 'Andorra la Vella',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
            ],
            [
                'name' => 'Angola',
                'iso2' => 'AO',
                'iso3' => 'AGO',
                'phone_code' => '+244',
                'currency_code' => 'AOA',
                'currency_name' => 'Angolan Kwanza',
                'capital' => 'Luanda',
                'region' => 'Africa',
                'subregion' => 'Middle Africa',
            ],
            [
                'name' => 'Antigua and Barbuda',
                'iso2' => 'AG',
                'iso3' => 'ATG',
                'phone_code' => '+1-268',
                'currency_code' => 'XCD',
                'currency_name' => 'Eastern Caribbean Dollar',
                'capital' => "Saint John's",
                'region' => 'Americas',
                'subregion' => 'Caribbean',
            ],
            [
                'name' => 'Argentina',
                'iso2' => 'AR',
                'iso3' => 'ARG',
                'phone_code' => '+54',
                'currency_code' => 'ARS',
                'currency_name' => 'Argentine Peso',
                'capital' => 'Buenos Aires',
                'region' => 'Americas',
                'subregion' => 'South America',
            ],
            [
                'name' => 'Armenia',
                'iso2' => 'AM',
                'iso3' => 'ARM',
                'phone_code' => '+374',
                'currency_code' => 'AMD',
                'currency_name' => 'Armenian Dram',
                'capital' => 'Yerevan',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
            ],
            [
                'name' => 'Australia',
                'iso2' => 'AU',
                'iso3' => 'AUS',
                'phone_code' => '+61',
                'currency_code' => 'AUD',
                'currency_name' => 'Australian Dollar',
                'capital' => 'Canberra',
                'region' => 'Oceania',
                'subregion' => 'Australia and New Zealand',
            ],
            [
                'name' => 'Austria',
                'iso2' => 'AT',
                'iso3' => 'AUT',
                'phone_code' => '+43',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'capital' => 'Vienna',
                'region' => 'Europe',
                'subregion' => 'Western Europe',
            ],
            [
                'name' => 'Azerbaijan',
                'iso2' => 'AZ',
                'iso3' => 'AZE',
                'phone_code' => '+994',
                'currency_code' => 'AZN',
                'currency_name' => 'Azerbaijani Manat',
                'capital' => 'Baku',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
            ],
            [
                'name' => 'Bahamas',
                'iso2' => 'BS',
                'iso3' => 'BHS',
                'phone_code' => '+1-242',
                'currency_code' => 'BSD',
                'currency_name' => 'Bahamian Dollar',
                'capital' => 'Nassau',
                'region' => 'Americas',
                'subregion' => 'Caribbean',
            ],
            [
                'name' => 'Bahrain',
                'iso2' => 'BH',
                'iso3' => 'BHR',
                'phone_code' => '+973',
                'currency_code' => 'BHD',
                'currency_name' => 'Bahraini Dinar',
                'capital' => 'Manama',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
            ],
            [
                'name' => 'Barbados',
                'iso2' => 'BB',
                'iso3' => 'BRB',
                'phone_code' => '+1-246',
                'currency_code' => 'BBD',
                'currency_name' => 'Barbadian Dollar',
                'capital' => 'Bridgetown',
                'region' => 'Americas',
                'subregion' => 'Caribbean',
            ],
            [
                'name' => 'Belarus',
                'iso2' => 'BY',
                'iso3' => 'BLR',
                'phone_code' => '+375',
                'currency_code' => 'BYN',
                'currency_name' => 'Belarusian Ruble',
                'capital' => 'Minsk',
                'region' => 'Europe',
                'subregion' => 'Eastern Europe',
            ],
            [
                'name' => 'Belgium',
                'iso2' => 'BE',
                'iso3' => 'BEL',
                'phone_code' => '+32',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'capital' => 'Brussels',
                'region' => 'Europe',
                'subregion' => 'Western Europe',
            ],
            [
                'name' => 'Belize',
                'iso2' => 'BZ',
                'iso3' => 'BLZ',
                'phone_code' => '+501',
                'currency_code' => 'BZD',
                'currency_name' => 'Belize Dollar',
                'capital' => 'Belmopan',
                'region' => 'Americas',
                'subregion' => 'Central America',
            ],
            [
                'name' => 'Benin',
                'iso2' => 'BJ',
                'iso3' => 'BEN',
                'phone_code' => '+229',
                'currency_code' => 'XOF',
                'currency_name' => 'West African CFA Franc',
                'capital' => 'Porto-Novo',
                'region' => 'Africa',
                'subregion' => 'Western Africa',
            ],
            [
                'name' => 'Bhutan',
                'iso2' => 'BT',
                'iso3' => 'BTN',
                'phone_code' => '+975',
                'currency_code' => 'BTN',
                'currency_name' => 'Bhutanese Ngultrum',
                'capital' => 'Thimphu',
                'region' => 'Asia',
                'subregion' => 'Southern Asia',
            ],
            [
                'name' => 'Bolivia',
                'iso2' => 'BO',
                'iso3' => 'BOL',
                'phone_code' => '+591',
                'currency_code' => 'BOB',
                'currency_name' => 'Bolivian Boliviano',
                'capital' => 'Sucre',
                'region' => 'Americas',
                'subregion' => 'South America',
            ],
            [
                'name' => 'Bosnia and Herzegovina',
                'iso2' => 'BA',
                'iso3' => 'BIH',
                'phone_code' => '+387',
                'currency_code' => 'BAM',
                'currency_name' => 'Bosnia and Herzegovina Convertible Mark',
                'capital' => 'Sarajevo',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
            ],
            [
                'name' => 'Botswana',
                'iso2' => 'BW',
                'iso3' => 'BWA',
                'phone_code' => '+267',
                'currency_code' => 'BWP',
                'currency_name' => 'Botswana Pula',
                'capital' => 'Gaborone',
                'region' => 'Africa',
                'subregion' => 'Southern Africa',
            ],
            [
                'name' => 'Brazil',
                'iso2' => 'BR',
                'iso3' => 'BRA',
                'phone_code' => '+55',
                'currency_code' => 'BRL',
                'currency_name' => 'Brazilian Real',
                'capital' => 'Brasília',
                'region' => 'Americas',
                'subregion' => 'South America',
            ],
            [
                'name' => 'Brunei',
                'iso2' => 'BN',
                'iso3' => 'BRN',
                'phone_code' => '+673',
                'currency_code' => 'BND',
                'currency_name' => 'Brunei Dollar',
                'capital' => 'Bandar Seri Begawan',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
            ],
            [
                'name' => 'Bulgaria',
                'iso2' => 'BG',
                'iso3' => 'BGR',
                'phone_code' => '+359',
                'currency_code' => 'BGN',
                'currency_name' => 'Bulgarian Lev',
                'capital' => 'Sofia',
                'region' => 'Europe',
                'subregion' => 'Eastern Europe',
            ],
            [
                'name' => 'Burkina Faso',
                'iso2' => 'BF',
                'iso3' => 'BFA',
                'phone_code' => '+226',
                'currency_code' => 'XOF',
                'currency_name' => 'West African CFA Franc',
                'capital' => 'Ouagadougou',
                'region' => 'Africa',
                'subregion' => 'Western Africa',
            ],
            [
                'name' => 'Burundi',
                'iso2' => 'BI',
                'iso3' => 'BDI',
                'phone_code' => '+257',
                'currency_code' => 'BIF',
                'currency_name' => 'Burundian Franc',
                'capital' => 'Gitega',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
            ],
            [
                'name' => 'Cabo Verde',
                'iso2' => 'CV',
                'iso3' => 'CPV',
                'phone_code' => '+238',
                'currency_code' => 'CVE',
                'currency_name' => 'Cape Verdean Escudo',
                'capital' => 'Praia',
                'region' => 'Africa',
                'subregion' => 'Western Africa',
            ],
            [
                'name' => 'Cambodia',
                'iso2' => 'KH',
                'iso3' => 'KHM',
                'phone_code' => '+855',
                'currency_code' => 'KHR',
                'currency_name' => 'Cambodian Riel',
                'capital' => 'Phnom Penh',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
            ],
            [
                'name' => 'Cameroon',
                'iso2' => 'CM',
                'iso3' => 'CMR',
                'phone_code' => '+237',
                'currency_code' => 'XAF',
                'currency_name' => 'Central African CFA Franc',
                'capital' => 'Yaoundé',
                'region' => 'Africa',
                'subregion' => 'Middle Africa',
            ],
            [
                'name' => 'Canada',
                'iso2' => 'CA',
                'iso3' => 'CAN',
                'phone_code' => '+1',
                'currency_code' => 'CAD',
                'currency_name' => 'Canadian Dollar',
                'capital' => 'Ottawa',
                'region' => 'Americas',
                'subregion' => 'Northern America',
            ],
            [
                'name' => 'Central African Republic',
                'iso2' => 'CF',
                'iso3' => 'CAF',
                'phone_code' => '+236',
                'currency_code' => 'XAF',
                'currency_name' => 'Central African CFA Franc',
                'capital' => 'Bangui',
                'region' => 'Africa',
                'subregion' => 'Middle Africa',
            ],
            [
                'name' => 'Chad',
                'iso2' => 'TD',
                'iso3' => 'TCD',
                'phone_code' => '+235',
                'currency_code' => 'XAF',
                'currency_name' => 'Central African CFA Franc',
                'capital' => "N'Djamena",
                'region' => 'Africa',
                'subregion' => 'Middle Africa',
            ],
            [
                'name' => 'Chile',
                'iso2' => 'CL',
                'iso3' => 'CHL',
                'phone_code' => '+56',
                'currency_code' => 'CLP',
                'currency_name' => 'Chilean Peso',
                'capital' => 'Santiago',
                'region' => 'Americas',
                'subregion' => 'South America',
            ],
            [
                'name' => 'China',
                'iso2' => 'CN',
                'iso3' => 'CHN',
                'phone_code' => '+86',
                'currency_code' => 'CNY',
                'currency_name' => 'Chinese Yuan',
                'capital' => 'Beijing',
                'region' => 'Asia',
                'subregion' => 'Eastern Asia',
            ],
            [
                'name' => 'Colombia',
                'iso2' => 'CO',
                'iso3' => 'COL',
                'phone_code' => '+57',
                'currency_code' => 'COP',
                'currency_name' => 'Colombian Peso',
                'capital' => 'Bogotá',
                'region' => 'Americas',
                'subregion' => 'South America',
            ],
            [
                'name' => 'Comoros',
                'iso2' => 'KM',
                'iso3' => 'COM',
                'phone_code' => '+269',
                'currency_code' => 'KMF',
                'currency_name' => 'Comorian Franc',
                'capital' => 'Moroni',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
            ],
            [
                'name' => 'Congo',
                'iso2' => 'CG',
                'iso3' => 'COG',
                'phone_code' => '+242',
                'currency_code' => 'XAF',
                'currency_name' => 'Central African CFA Franc',
                'capital' => 'Brazzaville',
                'region' => 'Africa',
                'subregion' => 'Middle Africa',
            ],
            [
                'name' => 'Costa Rica',
                'iso2' => 'CR',
                'iso3' => 'CRI',
                'phone_code' => '+506',
                'currency_code' => 'CRC',
                'currency_name' => 'Costa Rican Colón',
                'capital' => 'San José',
                'region' => 'Americas',
                'subregion' => 'Central America',
            ],
            [
                'name' => 'Côte d’Ivoire',
                'iso2' => 'CI',
                'iso3' => 'CIV',
                'phone_code' => '+225',
                'currency_code' => 'XOF',
                'currency_name' => 'West African CFA Franc',
                'capital' => 'Yamoussoukro',
                'region' => 'Africa',
                'subregion' => 'Western Africa',
            ],
            [
                'name' => 'Croatia',
                'iso2' => 'HR',
                'iso3' => 'HRV',
                'phone_code' => '+385',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'capital' => 'Zagreb',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
            ],
            [
                'name' => 'Cuba',
                'iso2' => 'CU',
                'iso3' => 'CUB',
                'phone_code' => '+53',
                'currency_code' => 'CUP',
                'currency_name' => 'Cuban Peso',
                'capital' => 'Havana',
                'region' => 'Americas',
                'subregion' => 'Caribbean',
            ],
            [
                'name' => 'Cyprus',
                'iso2' => 'CY',
                'iso3' => 'CYP',
                'phone_code' => '+357',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'capital' => 'Nicosia',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
            ],
            [
                'name' => 'Czechia',
                'iso2' => 'CZ',
                'iso3' => 'CZE',
                'phone_code' => '+420',
                'currency_code' => 'CZK',
                'currency_name' => 'Czech Koruna',
                'capital' => 'Prague',
                'region' => 'Europe',
                'subregion' => 'Eastern Europe',
            ],
            [
                'name' => 'Democratic Republic of the Congo',
                'iso2' => 'CD',
                'iso3' => 'COD',
                'phone_code' => '+243',
                'currency_code' => 'CDF',
                'currency_name' => 'Congolese Franc',
                'capital' => 'Kinshasa',
                'region' => 'Africa',
                'subregion' => 'Middle Africa',
            ],
            [
                'name' => 'Denmark',
                'iso2' => 'DK',
                'iso3' => 'DNK',
                'phone_code' => '+45',
                'currency_code' => 'DKK',
                'currency_name' => 'Danish Krone',
                'capital' => 'Copenhagen',
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
            ],
            [
                'name' => 'Djibouti',
                'iso2' => 'DJ',
                'iso3' => 'DJI',
                'phone_code' => '+253',
                'currency_code' => 'DJF',
                'currency_name' => 'Djiboutian Franc',
                'capital' => 'Djibouti',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
            ],
            [
                'name' => 'Dominica',
                'iso2' => 'DM',
                'iso3' => 'DMA',
                'phone_code' => '+1-767',
                'currency_code' => 'XCD',
                'currency_name' => 'Eastern Caribbean Dollar',
                'capital' => 'Roseau',
                'region' => 'Americas',
                'subregion' => 'Caribbean',
            ],
            [
                'name' => 'Dominican Republic',
                'iso2' => 'DO',
                'iso3' => 'DOM',
                'phone_code' => '+1-809',
                'currency_code' => 'DOP',
                'currency_name' => 'Dominican Peso',
                'capital' => 'Santo Domingo',
                'region' => 'Americas',
                'subregion' => 'Caribbean',
            ],
            [
                'name' => 'Ecuador',
                'iso2' => 'EC',
                'iso3' => 'ECU',
                'phone_code' => '+593',
                'currency_code' => 'USD',
                'currency_name' => 'United States Dollar',
                'capital' => 'Quito',
                'region' => 'Americas',
                'subregion' => 'South America',
            ],
            [
                'name' => 'Egypt',
                'iso2' => 'EG',
                'iso3' => 'EGY',
                'phone_code' => '+20',
                'currency_code' => 'EGP',
                'currency_name' => 'Egyptian Pound',
                'capital' => 'Cairo',
                'region' => 'Africa',
                'subregion' => 'Northern Africa',
            ],
            [
                'name' => 'El Salvador',
                'iso2' => 'SV',
                'iso3' => 'SLV',
                'phone_code' => '+503',
                'currency_code' => 'USD',
                'currency_name' => 'United States Dollar',
                'capital' => 'San Salvador',
                'region' => 'Americas',
                'subregion' => 'Central America',
            ],
            [
                'name' => 'Equatorial Guinea',
                'iso2' => 'GQ',
                'iso3' => 'GNQ',
                'phone_code' => '+240',
                'currency_code' => 'XAF',
                'currency_name' => 'Central African CFA Franc',
                'capital' => 'Malabo',
                'region' => 'Africa',
                'subregion' => 'Middle Africa',
            ],
            [
                'name' => 'Eritrea',
                'iso2' => 'ER',
                'iso3' => 'ERI',
                'phone_code' => '+291',
                'currency_code' => 'ERN',
                'currency_name' => 'Eritrean Nakfa',
                'capital' => 'Asmara',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
            ],
            [
                'name' => 'Estonia',
                'iso2' => 'EE',
                'iso3' => 'EST',
                'phone_code' => '+372',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'capital' => 'Tallinn',
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
            ],
            [
                'name' => 'Eswatini',
                'iso2' => 'SZ',
                'iso3' => 'SWZ',
                'phone_code' => '+268',
                'currency_code' => 'SZL',
                'currency_name' => 'Swazi Lilangeni',
                'capital' => 'Mbabane',
                'region' => 'Africa',
                'subregion' => 'Southern Africa',
            ],
            [
                'name' => 'Ethiopia',
                'iso2' => 'ET',
                'iso3' => 'ETH',
                'phone_code' => '+251',
                'currency_code' => 'ETB',
                'currency_name' => 'Ethiopian Birr',
                'capital' => 'Addis Ababa',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
            ],
            [
                'name' => 'Fiji',
                'iso2' => 'FJ',
                'iso3' => 'FJI',
                'phone_code' => '+679',
                'currency_code' => 'FJD',
                'currency_name' => 'Fijian Dollar',
                'capital' => 'Suva',
                'region' => 'Oceania',
                'subregion' => 'Melanesia',
            ],
            [
                'name' => 'Finland',
                'iso2' => 'FI',
                'iso3' => 'FIN',
                'phone_code' => '+358',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'capital' => 'Helsinki',
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
            ],
            [
                'name' => 'France',
                'iso2' => 'FR',
                'iso3' => 'FRA',
                'phone_code' => '+33',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'capital' => 'Paris',
                'region' => 'Europe',
                'subregion' => 'Western Europe',
            ],
            [
                'name' => 'Gabon',
                'iso2' => 'GA',
                'iso3' => 'GAB',
                'phone_code' => '+241',
                'currency_code' => 'XAF',
                'currency_name' => 'Central African CFA Franc',
                'capital' => 'Libreville',
                'region' => 'Africa',
                'subregion' => 'Middle Africa',
            ],
            [
                'name' => 'Gambia',
                'iso2' => 'GM',
                'iso3' => 'GMB',
                'phone_code' => '+220',
                'currency_code' => 'GMD',
                'currency_name' => 'Gambian Dalasi',
                'capital' => 'Banjul',
                'region' => 'Africa',
                'subregion' => 'Western Africa',
            ],
            [
                'name' => 'Georgia',
                'iso2' => 'GE',
                'iso3' => 'GEO',
                'phone_code' => '+995',
                'currency_code' => 'GEL',
                'currency_name' => 'Georgian Lari',
                'capital' => 'Tbilisi',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
            ],
            [
                'name' => 'Germany',
                'iso2' => 'DE',
                'iso3' => 'DEU',
                'phone_code' => '+49',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'capital' => 'Berlin',
                'region' => 'Europe',
                'subregion' => 'Western Europe',
            ],
            [
                'name' => 'Ghana',
                'iso2' => 'GH',
                'iso3' => 'GHA',
                'phone_code' => '+233',
                'currency_code' => 'GHS',
                'currency_name' => 'Ghanaian Cedi',
                'capital' => 'Accra',
                'region' => 'Africa',
                'subregion' => 'Western Africa',
            ],
            [
                'name' => 'Greece',
                'iso2' => 'GR',
                'iso3' => 'GRC',
                'phone_code' => '+30',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'capital' => 'Athens',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
            ],
            [
                'name' => 'Grenada',
                'iso2' => 'GD',
                'iso3' => 'GRD',
                'phone_code' => '+1-473',
                'currency_code' => 'XCD',
                'currency_name' => 'Eastern Caribbean Dollar',
                'capital' => "St. George's",
                'region' => 'Americas',
                'subregion' => 'Caribbean',
            ],
            [
                'name' => 'Guatemala',
                'iso2' => 'GT',
                'iso3' => 'GTM',
                'phone_code' => '+502',
                'currency_code' => 'GTQ',
                'currency_name' => 'Guatemalan Quetzal',
                'capital' => 'Guatemala City',
                'region' => 'Americas',
                'subregion' => 'Central America',
            ],
            [
                'name' => 'Guinea',
                'iso2' => 'GN',
                'iso3' => 'GIN',
                'phone_code' => '+224',
                'currency_code' => 'GNF',
                'currency_name' => 'Guinean Franc',
                'capital' => 'Conakry',
                'region' => 'Africa',
                'subregion' => 'Western Africa',
            ],
            [
                'name' => 'Guinea-Bissau',
                'iso2' => 'GW',
                'iso3' => 'GNB',
                'phone_code' => '+245',
                'currency_code' => 'XOF',
                'currency_name' => 'West African CFA Franc',
                'capital' => 'Bissau',
                'region' => 'Africa',
                'subregion' => 'Western Africa',
            ],
            [
                'name' => 'Guyana',
                'iso2' => 'GY',
                'iso3' => 'GUY',
                'phone_code' => '+592',
                'currency_code' => 'GYD',
                'currency_name' => 'Guyanese Dollar',
                'capital' => 'Georgetown',
                'region' => 'Americas',
                'subregion' => 'South America',
            ],
            [
                'name' => 'Haiti',
                'iso2' => 'HT',
                'iso3' => 'HTI',
                'phone_code' => '+509',
                'currency_code' => 'HTG',
                'currency_name' => 'Haitian Gourde',
                'capital' => 'Port-au-Prince',
                'region' => 'Americas',
                'subregion' => 'Caribbean',
            ],
            [
                'name' => 'Honduras',
                'iso2' => 'HN',
                'iso3' => 'HND',
                'phone_code' => '+504',
                'currency_code' => 'HNL',
                'currency_name' => 'Honduran Lempira',
                'capital' => 'Tegucigalpa',
                'region' => 'Americas',
                'subregion' => 'Central America',
            ],
            [
                'name' => 'Hungary',
                'iso2' => 'HU',
                'iso3' => 'HUN',
                'phone_code' => '+36',
                'currency_code' => 'HUF',
                'currency_name' => 'Hungarian Forint',
                'capital' => 'Budapest',
                'region' => 'Europe',
                'subregion' => 'Eastern Europe',
            ],
            [
                'name' => 'Iceland',
                'iso2' => 'IS',
                'iso3' => 'ISL',
                'phone_code' => '+354',
                'currency_code' => 'ISK',
                'currency_name' => 'Icelandic Króna',
                'capital' => 'Reykjavík',
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
            ],
            [
                'name' => 'India',
                'iso2' => 'IN',
                'iso3' => 'IND',
                'phone_code' => '+91',
                'currency_code' => 'INR',
                'currency_name' => 'Indian Rupee',
                'capital' => 'New Delhi',
                'region' => 'Asia',
                'subregion' => 'Southern Asia',
            ],
            [
                'name' => 'Indonesia',
                'iso2' => 'ID',
                'iso3' => 'IDN',
                'phone_code' => '+62',
                'currency_code' => 'IDR',
                'currency_name' => 'Indonesian Rupiah',
                'capital' => 'Jakarta',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
            ],
            [
                'name' => 'Iran',
                'iso2' => 'IR',
                'iso3' => 'IRN',
                'phone_code' => '+98',
                'currency_code' => 'IRR',
                'currency_name' => 'Iranian Rial',
                'capital' => 'Tehran',
                'region' => 'Asia',
                'subregion' => 'Southern Asia',
            ],
            [
                'name' => 'Iraq',
                'iso2' => 'IQ',
                'iso3' => 'IRQ',
                'phone_code' => '+964',
                'currency_code' => 'IQD',
                'currency_name' => 'Iraqi Dinar',
                'capital' => 'Baghdad',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
            ],
            [
                'name' => 'Ireland',
                'iso2' => 'IE',
                'iso3' => 'IRL',
                'phone_code' => '+353',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'capital' => 'Dublin',
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
            ],
            [
                'name' => 'Israel',
                'iso2' => 'IL',
                'iso3' => 'ISR',
                'phone_code' => '+972',
                'currency_code' => 'ILS',
                'currency_name' => 'Israeli New Shekel',
                'capital' => 'Jerusalem',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
            ],
            [
                'name' => 'Italy',
                'iso2' => 'IT',
                'iso3' => 'ITA',
                'phone_code' => '+39',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'capital' => 'Rome',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
            ],
            [
                'name' => 'Jamaica',
                'iso2' => 'JM',
                'iso3' => 'JAM',
                'phone_code' => '+1-876',
                'currency_code' => 'JMD',
                'currency_name' => 'Jamaican Dollar',
                'capital' => 'Kingston',
                'region' => 'Americas',
                'subregion' => 'Caribbean',
            ],
            [
                'name' => 'Japan',
                'iso2' => 'JP',
                'iso3' => 'JPN',
                'phone_code' => '+81',
                'currency_code' => 'JPY',
                'currency_name' => 'Japanese Yen',
                'capital' => 'Tokyo',
                'region' => 'Asia',
                'subregion' => 'Eastern Asia',
            ],
            [
                'name' => 'Jordan',
                'iso2' => 'JO',
                'iso3' => 'JOR',
                'phone_code' => '+962',
                'currency_code' => 'JOD',
                'currency_name' => 'Jordanian Dinar',
                'capital' => 'Amman',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
            ],
            [
                'name' => 'Kazakhstan',
                'iso2' => 'KZ',
                'iso3' => 'KAZ',
                'phone_code' => '+7',
                'currency_code' => 'KZT',
                'currency_name' => 'Kazakhstani Tenge',
                'capital' => 'Astana',
                'region' => 'Asia',
                'subregion' => 'Central Asia',
            ],
            [
                'name' => 'Kenya',
                'iso2' => 'KE',
                'iso3' => 'KEN',
                'phone_code' => '+254',
                'currency_code' => 'KES',
                'currency_name' => 'Kenyan Shilling',
                'capital' => 'Nairobi',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
            ],
            [
                'name' => 'Kiribati',
                'iso2' => 'KI',
                'iso3' => 'KIR',
                'phone_code' => '+686',
                'currency_code' => 'AUD',
                'currency_name' => 'Australian Dollar',
                'capital' => 'South Tarawa',
                'region' => 'Oceania',
                'subregion' => 'Micronesia',
            ],
            [
                'name' => 'Kuwait',
                'iso2' => 'KW',
                'iso3' => 'KWT',
                'phone_code' => '+965',
                'currency_code' => 'KWD',
                'currency_name' => 'Kuwaiti Dinar',
                'capital' => 'Kuwait City',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
            ],
            [
                'name' => 'Kyrgyzstan',
                'iso2' => 'KG',
                'iso3' => 'KGZ',
                'phone_code' => '+996',
                'currency_code' => 'KGS',
                'currency_name' => 'Kyrgyzstani Som',
                'capital' => 'Bishkek',
                'region' => 'Asia',
                'subregion' => 'Central Asia',
            ],
            [
                'name' => 'Laos',
                'iso2' => 'LA',
                'iso3' => 'LAO',
                'phone_code' => '+856',
                'currency_code' => 'LAK',
                'currency_name' => 'Lao Kip',
                'capital' => 'Vientiane',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
            ],
            [
                'name' => 'Latvia',
                'iso2' => 'LV',
                'iso3' => 'LVA',
                'phone_code' => '+371',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'capital' => 'Riga',
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
            ],
            [
                'name' => 'Lebanon',
                'iso2' => 'LB',
                'iso3' => 'LBN',
                'phone_code' => '+961',
                'currency_code' => 'LBP',
                'currency_name' => 'Lebanese Pound',
                'capital' => 'Beirut',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
            ],
            [
                'name' => 'Lesotho',
                'iso2' => 'LS',
                'iso3' => 'LSO',
                'phone_code' => '+266',
                'currency_code' => 'LSL',
                'currency_name' => 'Lesotho Loti',
                'capital' => 'Maseru',
                'region' => 'Africa',
                'subregion' => 'Southern Africa',
            ],
            [
                'name' => 'Liberia',
                'iso2' => 'LR',
                'iso3' => 'LBR',
                'phone_code' => '+231',
                'currency_code' => 'LRD',
                'currency_name' => 'Liberian Dollar',
                'capital' => 'Monrovia',
                'region' => 'Africa',
                'subregion' => 'Western Africa',
            ],
            [
                'name' => 'Libya',
                'iso2' => 'LY',
                'iso3' => 'LBY',
                'phone_code' => '+218',
                'currency_code' => 'LYD',
                'currency_name' => 'Libyan Dinar',
                'capital' => 'Tripoli',
                'region' => 'Africa',
                'subregion' => 'Northern Africa',
            ],
            [
                'name' => 'Liechtenstein',
                'iso2' => 'LI',
                'iso3' => 'LIE',
                'phone_code' => '+423',
                'currency_code' => 'CHF',
                'currency_name' => 'Swiss Franc',
                'capital' => 'Vaduz',
                'region' => 'Europe',
                'subregion' => 'Western Europe',
            ],
            [
                'name' => 'Lithuania',
                'iso2' => 'LT',
                'iso3' => 'LTU',
                'phone_code' => '+370',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'capital' => 'Vilnius',
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
            ],
            [
                'name' => 'Luxembourg',
                'iso2' => 'LU',
                'iso3' => 'LUX',
                'phone_code' => '+352',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'capital' => 'Luxembourg',
                'region' => 'Europe',
                'subregion' => 'Western Europe',
            ],
            [
                'name' => 'Madagascar',
                'iso2' => 'MG',
                'iso3' => 'MDG',
                'phone_code' => '+261',
                'currency_code' => 'MGA',
                'currency_name' => 'Malagasy Ariary',
                'capital' => 'Antananarivo',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
            ],
            [
                'name' => 'Malawi',
                'iso2' => 'MW',
                'iso3' => 'MWI',
                'phone_code' => '+265',
                'currency_code' => 'MWK',
                'currency_name' => 'Malawian Kwacha',
                'capital' => 'Lilongwe',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
            ],
            [
                'name' => 'Malaysia',
                'iso2' => 'MY',
                'iso3' => 'MYS',
                'phone_code' => '+60',
                'currency_code' => 'MYR',
                'currency_name' => 'Malaysian Ringgit',
                'capital' => 'Kuala Lumpur',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
            ],
            [
                'name' => 'Maldives',
                'iso2' => 'MV',
                'iso3' => 'MDV',
                'phone_code' => '+960',
                'currency_code' => 'MVR',
                'currency_name' => 'Maldivian Rufiyaa',
                'capital' => 'Malé',
                'region' => 'Asia',
                'subregion' => 'Southern Asia',
            ],
            [
                'name' => 'Mali',
                'iso2' => 'ML',
                'iso3' => 'MLI',
                'phone_code' => '+223',
                'currency_code' => 'XOF',
                'currency_name' => 'West African CFA Franc',
                'capital' => 'Bamako',
                'region' => 'Africa',
                'subregion' => 'Western Africa',
            ],
            [
                'name' => 'Malta',
                'iso2' => 'MT',
                'iso3' => 'MLT',
                'phone_code' => '+356',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'capital' => 'Valletta',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
            ],
            [
                'name' => 'Marshall Islands',
                'iso2' => 'MH',
                'iso3' => 'MHL',
                'phone_code' => '+692',
                'currency_code' => 'USD',
                'currency_name' => 'United States Dollar',
                'capital' => 'Majuro',
                'region' => 'Oceania',
                'subregion' => 'Micronesia',
            ],
            [
                'name' => 'Mauritania',
                'iso2' => 'MR',
                'iso3' => 'MRT',
                'phone_code' => '+222',
                'currency_code' => 'MRU',
                'currency_name' => 'Mauritanian Ouguiya',
                'capital' => 'Nouakchott',
                'region' => 'Africa',
                'subregion' => 'Western Africa',
            ],
            [
                'name' => 'Mauritius',
                'iso2' => 'MU',
                'iso3' => 'MUS',
                'phone_code' => '+230',
                'currency_code' => 'MUR',
                'currency_name' => 'Mauritian Rupee',
                'capital' => 'Port Louis',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
            ],
            [
                'name' => 'Mexico',
                'iso2' => 'MX',
                'iso3' => 'MEX',
                'phone_code' => '+52',
                'currency_code' => 'MXN',
                'currency_name' => 'Mexican Peso',
                'capital' => 'Mexico City',
                'region' => 'Americas',
                'subregion' => 'Central America',
            ],
            [
                'name' => 'Micronesia',
                'iso2' => 'FM',
                'iso3' => 'FSM',
                'phone_code' => '+691',
                'currency_code' => 'USD',
                'currency_name' => 'United States Dollar',
                'capital' => 'Palikir',
                'region' => 'Oceania',
                'subregion' => 'Micronesia',
            ],
            [
                'name' => 'Moldova',
                'iso2' => 'MD',
                'iso3' => 'MDA',
                'phone_code' => '+373',
                'currency_code' => 'MDL',
                'currency_name' => 'Moldovan Leu',
                'capital' => 'Chișinău',
                'region' => 'Europe',
                'subregion' => 'Eastern Europe',
            ],
            [
                'name' => 'Monaco',
                'iso2' => 'MC',
                'iso3' => 'MCO',
                'phone_code' => '+377',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'capital' => 'Monaco',
                'region' => 'Europe',
                'subregion' => 'Western Europe',
            ],
            [
                'name' => 'Mongolia',
                'iso2' => 'MN',
                'iso3' => 'MNG',
                'phone_code' => '+976',
                'currency_code' => 'MNT',
                'currency_name' => 'Mongolian Tögrög',
                'capital' => 'Ulaanbaatar',
                'region' => 'Asia',
                'subregion' => 'Eastern Asia',
            ],
            [
                'name' => 'Montenegro',
                'iso2' => 'ME',
                'iso3' => 'MNE',
                'phone_code' => '+382',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'capital' => 'Podgorica',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
            ],
            [
                'name' => 'Morocco',
                'iso2' => 'MA',
                'iso3' => 'MAR',
                'phone_code' => '+212',
                'currency_code' => 'MAD',
                'currency_name' => 'Moroccan Dirham',
                'capital' => 'Rabat',
                'region' => 'Africa',
                'subregion' => 'Northern Africa',
            ],
            [
                'name' => 'Mozambique',
                'iso2' => 'MZ',
                'iso3' => 'MOZ',
                'phone_code' => '+258',
                'currency_code' => 'MZN',
                'currency_name' => 'Mozambican Metical',
                'capital' => 'Maputo',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
            ],
            [
                'name' => 'Myanmar',
                'iso2' => 'MM',
                'iso3' => 'MMR',
                'phone_code' => '+95',
                'currency_code' => 'MMK',
                'currency_name' => 'Myanmar Kyat',
                'capital' => 'Naypyidaw',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
            ],
            [
                'name' => 'Namibia',
                'iso2' => 'NA',
                'iso3' => 'NAM',
                'phone_code' => '+264',
                'currency_code' => 'NAD',
                'currency_name' => 'Namibian Dollar',
                'capital' => 'Windhoek',
                'region' => 'Africa',
                'subregion' => 'Southern Africa',
            ],
            [
                'name' => 'Nauru',
                'iso2' => 'NR',
                'iso3' => 'NRU',
                'phone_code' => '+674',
                'currency_code' => 'AUD',
                'currency_name' => 'Australian Dollar',
                'capital' => 'Yaren',
                'region' => 'Oceania',
                'subregion' => 'Micronesia',
            ],
            [
                'name' => 'Nepal',
                'iso2' => 'NP',
                'iso3' => 'NPL',
                'phone_code' => '+977',
                'currency_code' => 'NPR',
                'currency_name' => 'Nepalese Rupee',
                'capital' => 'Kathmandu',
                'region' => 'Asia',
                'subregion' => 'Southern Asia',
            ],
            [
                'name' => 'Netherlands',
                'iso2' => 'NL',
                'iso3' => 'NLD',
                'phone_code' => '+31',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'capital' => 'Amsterdam',
                'region' => 'Europe',
                'subregion' => 'Western Europe',
            ],
            [
                'name' => 'New Zealand',
                'iso2' => 'NZ',
                'iso3' => 'NZL',
                'phone_code' => '+64',
                'currency_code' => 'NZD',
                'currency_name' => 'New Zealand Dollar',
                'capital' => 'Wellington',
                'region' => 'Oceania',
                'subregion' => 'Australia and New Zealand',
            ],
            [
                'name' => 'Nicaragua',
                'iso2' => 'NI',
                'iso3' => 'NIC',
                'phone_code' => '+505',
                'currency_code' => 'NIO',
                'currency_name' => 'Nicaraguan Córdoba',
                'capital' => 'Managua',
                'region' => 'Americas',
                'subregion' => 'Central America',
            ],
            [
                'name' => 'Niger',
                'iso2' => 'NE',
                'iso3' => 'NER',
                'phone_code' => '+227',
                'currency_code' => 'XOF',
                'currency_name' => 'West African CFA Franc',
                'capital' => 'Niamey',
                'region' => 'Africa',
                'subregion' => 'Western Africa',
            ],
            [
                'name' => 'Nigeria',
                'iso2' => 'NG',
                'iso3' => 'NGA',
                'phone_code' => '+234',
                'currency_code' => 'NGN',
                'currency_name' => 'Nigerian Naira',
                'capital' => 'Abuja',
                'region' => 'Africa',
                'subregion' => 'Western Africa',
            ],
            [
                'name' => 'North Korea',
                'iso2' => 'KP',
                'iso3' => 'PRK',
                'phone_code' => '+850',
                'currency_code' => 'KPW',
                'currency_name' => 'North Korean Won',
                'capital' => 'Pyongyang',
                'region' => 'Asia',
                'subregion' => 'Eastern Asia',
            ],
            [
                'name' => 'North Macedonia',
                'iso2' => 'MK',
                'iso3' => 'MKD',
                'phone_code' => '+389',
                'currency_code' => 'MKD',
                'currency_name' => 'Macedonian Denar',
                'capital' => 'Skopje',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
            ],
            [
                'name' => 'Norway',
                'iso2' => 'NO',
                'iso3' => 'NOR',
                'phone_code' => '+47',
                'currency_code' => 'NOK',
                'currency_name' => 'Norwegian Krone',
                'capital' => 'Oslo',
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
            ],
            [
                'name' => 'Oman',
                'iso2' => 'OM',
                'iso3' => 'OMN',
                'phone_code' => '+968',
                'currency_code' => 'OMR',
                'currency_name' => 'Omani Rial',
                'capital' => 'Muscat',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
            ],
            [
                'name' => 'Pakistan',
                'iso2' => 'PK',
                'iso3' => 'PAK',
                'phone_code' => '+92',
                'currency_code' => 'PKR',
                'currency_name' => 'Pakistani Rupee',
                'capital' => 'Islamabad',
                'region' => 'Asia',
                'subregion' => 'Southern Asia',
            ],
            [
                'name' => 'Palau',
                'iso2' => 'PW',
                'iso3' => 'PLW',
                'phone_code' => '+680',
                'currency_code' => 'USD',
                'currency_name' => 'United States Dollar',
                'capital' => 'Ngerulmud',
                'region' => 'Oceania',
                'subregion' => 'Micronesia',
            ],
            [
                'name' => 'Palestine',
                'iso2' => 'PS',
                'iso3' => 'PSE',
                'phone_code' => '+970',
                'currency_code' => 'ILS',
                'currency_name' => 'Israeli New Shekel',
                'capital' => 'Ramallah',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
            ],
            [
                'name' => 'Panama',
                'iso2' => 'PA',
                'iso3' => 'PAN',
                'phone_code' => '+507',
                'currency_code' => 'PAB',
                'currency_name' => 'Panamanian Balboa',
                'capital' => 'Panama City',
                'region' => 'Americas',
                'subregion' => 'Central America',
            ],
            [
                'name' => 'Papua New Guinea',
                'iso2' => 'PG',
                'iso3' => 'PNG',
                'phone_code' => '+675',
                'currency_code' => 'PGK',
                'currency_name' => 'Papua New Guinean Kina',
                'capital' => 'Port Moresby',
                'region' => 'Oceania',
                'subregion' => 'Melanesia',
            ],
            [
                'name' => 'Paraguay',
                'iso2' => 'PY',
                'iso3' => 'PRY',
                'phone_code' => '+595',
                'currency_code' => 'PYG',
                'currency_name' => 'Paraguayan Guaraní',
                'capital' => 'Asunción',
                'region' => 'Americas',
                'subregion' => 'South America',
            ],
            [
                'name' => 'Peru',
                'iso2' => 'PE',
                'iso3' => 'PER',
                'phone_code' => '+51',
                'currency_code' => 'PEN',
                'currency_name' => 'Peruvian Sol',
                'capital' => 'Lima',
                'region' => 'Americas',
                'subregion' => 'South America',
            ],
            [
                'name' => 'Philippines',
                'iso2' => 'PH',
                'iso3' => 'PHL',
                'phone_code' => '+63',
                'currency_code' => 'PHP',
                'currency_name' => 'Philippine Peso',
                'capital' => 'Manila',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
            ],
            [
                'name' => 'Poland',
                'iso2' => 'PL',
                'iso3' => 'POL',
                'phone_code' => '+48',
                'currency_code' => 'PLN',
                'currency_name' => 'Polish Złoty',
                'capital' => 'Warsaw',
                'region' => 'Europe',
                'subregion' => 'Eastern Europe',
            ],
            [
                'name' => 'Portugal',
                'iso2' => 'PT',
                'iso3' => 'PRT',
                'phone_code' => '+351',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'capital' => 'Lisbon',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
            ],
            [
                'name' => 'Qatar',
                'iso2' => 'QA',
                'iso3' => 'QAT',
                'phone_code' => '+974',
                'currency_code' => 'QAR',
                'currency_name' => 'Qatari Riyal',
                'capital' => 'Doha',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
            ],
            [
                'name' => 'Romania',
                'iso2' => 'RO',
                'iso3' => 'ROU',
                'phone_code' => '+40',
                'currency_code' => 'RON',
                'currency_name' => 'Romanian Leu',
                'capital' => 'Bucharest',
                'region' => 'Europe',
                'subregion' => 'Eastern Europe',
            ],
            [
                'name' => 'Russia',
                'iso2' => 'RU',
                'iso3' => 'RUS',
                'phone_code' => '+7',
                'currency_code' => 'RUB',
                'currency_name' => 'Russian Ruble',
                'capital' => 'Moscow',
                'region' => 'Europe',
                'subregion' => 'Eastern Europe',
            ],
            [
                'name' => 'Rwanda',
                'iso2' => 'RW',
                'iso3' => 'RWA',
                'phone_code' => '+250',
                'currency_code' => 'RWF',
                'currency_name' => 'Rwandan Franc',
                'capital' => 'Kigali',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
            ],
            [
                'name' => 'Saint Kitts and Nevis',
                'iso2' => 'KN',
                'iso3' => 'KNA',
                'phone_code' => '+1-869',
                'currency_code' => 'XCD',
                'currency_name' => 'Eastern Caribbean Dollar',
                'capital' => 'Basseterre',
                'region' => 'Americas',
                'subregion' => 'Caribbean',
            ],
            [
                'name' => 'Saint Lucia',
                'iso2' => 'LC',
                'iso3' => 'LCA',
                'phone_code' => '+1-758',
                'currency_code' => 'XCD',
                'currency_name' => 'Eastern Caribbean Dollar',
                'capital' => 'Castries',
                'region' => 'Americas',
                'subregion' => 'Caribbean',
            ],
            [
                'name' => 'Saint Vincent and the Grenadines',
                'iso2' => 'VC',
                'iso3' => 'VCT',
                'phone_code' => '+1-784',
                'currency_code' => 'XCD',
                'currency_name' => 'Eastern Caribbean Dollar',
                'capital' => 'Kingstown',
                'region' => 'Americas',
                'subregion' => 'Caribbean',
            ],
            [
                'name' => 'Samoa',
                'iso2' => 'WS',
                'iso3' => 'WSM',
                'phone_code' => '+685',
                'currency_code' => 'WST',
                'currency_name' => 'Samoan Tālā',
                'capital' => 'Apia',
                'region' => 'Oceania',
                'subregion' => 'Polynesia',
            ],
            [
                'name' => 'San Marino',
                'iso2' => 'SM',
                'iso3' => 'SMR',
                'phone_code' => '+378',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'capital' => 'San Marino',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
            ],
            [
                'name' => 'São Tomé and Príncipe',
                'iso2' => 'ST',
                'iso3' => 'STP',
                'phone_code' => '+239',
                'currency_code' => 'STN',
                'currency_name' => 'São Tomé and Príncipe Dobra',
                'capital' => 'São Tomé',
                'region' => 'Africa',
                'subregion' => 'Middle Africa',
            ],
            [
                'name' => 'Saudi Arabia',
                'iso2' => 'SA',
                'iso3' => 'SAU',
                'phone_code' => '+966',
                'currency_code' => 'SAR',
                'currency_name' => 'Saudi Riyal',
                'capital' => 'Riyadh',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
            ],
            [
                'name' => 'Senegal',
                'iso2' => 'SN',
                'iso3' => 'SEN',
                'phone_code' => '+221',
                'currency_code' => 'XOF',
                'currency_name' => 'West African CFA Franc',
                'capital' => 'Dakar',
                'region' => 'Africa',
                'subregion' => 'Western Africa',
            ],
            [
                'name' => 'Serbia',
                'iso2' => 'RS',
                'iso3' => 'SRB',
                'phone_code' => '+381',
                'currency_code' => 'RSD',
                'currency_name' => 'Serbian Dinar',
                'capital' => 'Belgrade',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
            ],
            [
                'name' => 'Seychelles',
                'iso2' => 'SC',
                'iso3' => 'SYC',
                'phone_code' => '+248',
                'currency_code' => 'SCR',
                'currency_name' => 'Seychellois Rupee',
                'capital' => 'Victoria',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
            ],
            [
                'name' => 'Sierra Leone',
                'iso2' => 'SL',
                'iso3' => 'SLE',
                'phone_code' => '+232',
                'currency_code' => 'SLE',
                'currency_name' => 'Sierra Leonean Leone',
                'capital' => 'Freetown',
                'region' => 'Africa',
                'subregion' => 'Western Africa',
            ],
            [
                'name' => 'Singapore',
                'iso2' => 'SG',
                'iso3' => 'SGP',
                'phone_code' => '+65',
                'currency_code' => 'SGD',
                'currency_name' => 'Singapore Dollar',
                'capital' => 'Singapore',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
            ],
            [
                'name' => 'Slovakia',
                'iso2' => 'SK',
                'iso3' => 'SVK',
                'phone_code' => '+421',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'capital' => 'Bratislava',
                'region' => 'Europe',
                'subregion' => 'Eastern Europe',
            ],
            [
                'name' => 'Slovenia',
                'iso2' => 'SI',
                'iso3' => 'SVN',
                'phone_code' => '+386',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'capital' => 'Ljubljana',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
            ],
            [
                'name' => 'Solomon Islands',
                'iso2' => 'SB',
                'iso3' => 'SLB',
                'phone_code' => '+677',
                'currency_code' => 'SBD',
                'currency_name' => 'Solomon Islands Dollar',
                'capital' => 'Honiara',
                'region' => 'Oceania',
                'subregion' => 'Melanesia',
            ],
            [
                'name' => 'Somalia',
                'iso2' => 'SO',
                'iso3' => 'SOM',
                'phone_code' => '+252',
                'currency_code' => 'SOS',
                'currency_name' => 'Somali Shilling',
                'capital' => 'Mogadishu',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
            ],
            [
                'name' => 'South Africa',
                'iso2' => 'ZA',
                'iso3' => 'ZAF',
                'phone_code' => '+27',
                'currency_code' => 'ZAR',
                'currency_name' => 'South African Rand',
                'capital' => 'Pretoria',
                'region' => 'Africa',
                'subregion' => 'Southern Africa',
            ],
            [
                'name' => 'South Korea',
                'iso2' => 'KR',
                'iso3' => 'KOR',
                'phone_code' => '+82',
                'currency_code' => 'KRW',
                'currency_name' => 'South Korean Won',
                'capital' => 'Seoul',
                'region' => 'Asia',
                'subregion' => 'Eastern Asia',
            ],
            [
                'name' => 'South Sudan',
                'iso2' => 'SS',
                'iso3' => 'SSD',
                'phone_code' => '+211',
                'currency_code' => 'SSP',
                'currency_name' => 'South Sudanese Pound',
                'capital' => 'Juba',
                'region' => 'Africa',
                'subregion' => 'Middle Africa',
            ],
            [
                'name' => 'Spain',
                'iso2' => 'ES',
                'iso3' => 'ESP',
                'phone_code' => '+34',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'capital' => 'Madrid',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
            ],
            [
                'name' => 'Sri Lanka',
                'iso2' => 'LK',
                'iso3' => 'LKA',
                'phone_code' => '+94',
                'currency_code' => 'LKR',
                'currency_name' => 'Sri Lankan Rupee',
                'capital' => 'Sri Jayawardenepura Kotte',
                'region' => 'Asia',
                'subregion' => 'Southern Asia',
            ],
            [
                'name' => 'Sudan',
                'iso2' => 'SD',
                'iso3' => 'SDN',
                'phone_code' => '+249',
                'currency_code' => 'SDG',
                'currency_name' => 'Sudanese Pound',
                'capital' => 'Khartoum',
                'region' => 'Africa',
                'subregion' => 'Northern Africa',
            ],
            [
                'name' => 'Suriname',
                'iso2' => 'SR',
                'iso3' => 'SUR',
                'phone_code' => '+597',
                'currency_code' => 'SRD',
                'currency_name' => 'Surinamese Dollar',
                'capital' => 'Paramaribo',
                'region' => 'Americas',
                'subregion' => 'South America',
            ],
            [
                'name' => 'Sweden',
                'iso2' => 'SE',
                'iso3' => 'SWE',
                'phone_code' => '+46',
                'currency_code' => 'SEK',
                'currency_name' => 'Swedish Krona',
                'capital' => 'Stockholm',
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
            ],
            [
                'name' => 'Switzerland',
                'iso2' => 'CH',
                'iso3' => 'CHE',
                'phone_code' => '+41',
                'currency_code' => 'CHF',
                'currency_name' => 'Swiss Franc',
                'capital' => 'Bern',
                'region' => 'Europe',
                'subregion' => 'Western Europe',
            ],
            [
                'name' => 'Syria',
                'iso2' => 'SY',
                'iso3' => 'SYR',
                'phone_code' => '+963',
                'currency_code' => 'SYP',
                'currency_name' => 'Syrian Pound',
                'capital' => 'Damascus',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
            ],
            [
                'name' => 'Tajikistan',
                'iso2' => 'TJ',
                'iso3' => 'TJK',
                'phone_code' => '+992',
                'currency_code' => 'TJS',
                'currency_name' => 'Tajikistani Somoni',
                'capital' => 'Dushanbe',
                'region' => 'Asia',
                'subregion' => 'Central Asia',
            ],
            [
                'name' => 'Tanzania',
                'iso2' => 'TZ',
                'iso3' => 'TZA',
                'phone_code' => '+255',
                'currency_code' => 'TZS',
                'currency_name' => 'Tanzanian Shilling',
                'capital' => 'Dodoma',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
            ],
            [
                'name' => 'Thailand',
                'iso2' => 'TH',
                'iso3' => 'THA',
                'phone_code' => '+66',
                'currency_code' => 'THB',
                'currency_name' => 'Thai Baht',
                'capital' => 'Bangkok',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
            ],
            [
                'name' => 'Timor-Leste',
                'iso2' => 'TL',
                'iso3' => 'TLS',
                'phone_code' => '+670',
                'currency_code' => 'USD',
                'currency_name' => 'United States Dollar',
                'capital' => 'Dili',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
            ],
            [
                'name' => 'Togo',
                'iso2' => 'TG',
                'iso3' => 'TGO',
                'phone_code' => '+228',
                'currency_code' => 'XOF',
                'currency_name' => 'West African CFA Franc',
                'capital' => 'Lomé',
                'region' => 'Africa',
                'subregion' => 'Western Africa',
            ],
            [
                'name' => 'Tonga',
                'iso2' => 'TO',
                'iso3' => 'TON',
                'phone_code' => '+676',
                'currency_code' => 'TOP',
                'currency_name' => 'Tongan Paʻanga',
                'capital' => "Nuku'alofa",
                'region' => 'Oceania',
                'subregion' => 'Polynesia',
            ],
            [
                'name' => 'Trinidad and Tobago',
                'iso2' => 'TT',
                'iso3' => 'TTO',
                'phone_code' => '+1-868',
                'currency_code' => 'TTD',
                'currency_name' => 'Trinidad and Tobago Dollar',
                'capital' => 'Port of Spain',
                'region' => 'Americas',
                'subregion' => 'Caribbean',
            ],
            [
                'name' => 'Tunisia',
                'iso2' => 'TN',
                'iso3' => 'TUN',
                'phone_code' => '+216',
                'currency_code' => 'TND',
                'currency_name' => 'Tunisian Dinar',
                'capital' => 'Tunis',
                'region' => 'Africa',
                'subregion' => 'Northern Africa',
            ],
            [
                'name' => 'Türkiye',
                'iso2' => 'TR',
                'iso3' => 'TUR',
                'phone_code' => '+90',
                'currency_code' => 'TRY',
                'currency_name' => 'Turkish Lira',
                'capital' => 'Ankara',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
            ],
            [
                'name' => 'Turkmenistan',
                'iso2' => 'TM',
                'iso3' => 'TKM',
                'phone_code' => '+993',
                'currency_code' => 'TMT',
                'currency_name' => 'Turkmenistan Manat',
                'capital' => 'Ashgabat',
                'region' => 'Asia',
                'subregion' => 'Central Asia',
            ],
            [
                'name' => 'Tuvalu',
                'iso2' => 'TV',
                'iso3' => 'TUV',
                'phone_code' => '+688',
                'currency_code' => 'AUD',
                'currency_name' => 'Australian Dollar',
                'capital' => 'Funafuti',
                'region' => 'Oceania',
                'subregion' => 'Polynesia',
            ],
            [
                'name' => 'Uganda',
                'iso2' => 'UG',
                'iso3' => 'UGA',
                'phone_code' => '+256',
                'currency_code' => 'UGX',
                'currency_name' => 'Ugandan Shilling',
                'capital' => 'Kampala',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
            ],
            [
                'name' => 'Ukraine',
                'iso2' => 'UA',
                'iso3' => 'UKR',
                'phone_code' => '+380',
                'currency_code' => 'UAH',
                'currency_name' => 'Ukrainian Hryvnia',
                'capital' => 'Kyiv',
                'region' => 'Europe',
                'subregion' => 'Eastern Europe',
            ],
            [
                'name' => 'United Arab Emirates',
                'iso2' => 'AE',
                'iso3' => 'ARE',
                'phone_code' => '+971',
                'currency_code' => 'AED',
                'currency_name' => 'United Arab Emirates Dirham',
                'capital' => 'Abu Dhabi',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
            ],
            [
                'name' => 'United Kingdom',
                'iso2' => 'GB',
                'iso3' => 'GBR',
                'phone_code' => '+44',
                'currency_code' => 'GBP',
                'currency_name' => 'Pound Sterling',
                'capital' => 'London',
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
            ],
            [
                'name' => 'United States',
                'iso2' => 'US',
                'iso3' => 'USA',
                'phone_code' => '+1',
                'currency_code' => 'USD',
                'currency_name' => 'United States Dollar',
                'capital' => 'Washington, D.C.',
                'region' => 'Americas',
                'subregion' => 'Northern America',
            ],
            [
                'name' => 'Uruguay',
                'iso2' => 'UY',
                'iso3' => 'URY',
                'phone_code' => '+598',
                'currency_code' => 'UYU',
                'currency_name' => 'Uruguayan Peso',
                'capital' => 'Montevideo',
                'region' => 'Americas',
                'subregion' => 'South America',
            ],
            [
                'name' => 'Uzbekistan',
                'iso2' => 'UZ',
                'iso3' => 'UZB',
                'phone_code' => '+998',
                'currency_code' => 'UZS',
                'currency_name' => 'Uzbekistani Som',
                'capital' => 'Tashkent',
                'region' => 'Asia',
                'subregion' => 'Central Asia',
            ],
            [
                'name' => 'Vanuatu',
                'iso2' => 'VU',
                'iso3' => 'VUT',
                'phone_code' => '+678',
                'currency_code' => 'VUV',
                'currency_name' => 'Vanuatu Vatu',
                'capital' => 'Port Vila',
                'region' => 'Oceania',
                'subregion' => 'Melanesia',
            ],
            [
                'name' => 'Vatican City',
                'iso2' => 'VA',
                'iso3' => 'VAT',
                'phone_code' => '+39',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'capital' => 'Vatican City',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
            ],
            [
                'name' => 'Venezuela',
                'iso2' => 'VE',
                'iso3' => 'VEN',
                'phone_code' => '+58',
                'currency_code' => 'VES',
                'currency_name' => 'Venezuelan Bolívar',
                'capital' => 'Caracas',
                'region' => 'Americas',
                'subregion' => 'South America',
            ],
            [
                'name' => 'Vietnam',
                'iso2' => 'VN',
                'iso3' => 'VNM',
                'phone_code' => '+84',
                'currency_code' => 'VND',
                'currency_name' => 'Vietnamese Đồng',
                'capital' => 'Hanoi',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
            ],
            [
                'name' => 'Yemen',
                'iso2' => 'YE',
                'iso3' => 'YEM',
                'phone_code' => '+967',
                'currency_code' => 'YER',
                'currency_name' => 'Yemeni Rial',
                'capital' => "Sana'a",
                'region' => 'Asia',
                'subregion' => 'Western Asia',
            ],
            [
                'name' => 'Zambia',
                'iso2' => 'ZM',
                'iso3' => 'ZMB',
                'phone_code' => '+260',
                'currency_code' => 'ZMW',
                'currency_name' => 'Zambian Kwacha',
                'capital' => 'Lusaka',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
            ],
            [
                'name' => 'Zimbabwe',
                'iso2' => 'ZW',
                'iso3' => 'ZWE',
                'phone_code' => '+263',
                'currency_code' => 'ZWG',
                'currency_name' => 'Zimbabwe Gold',
                'capital' => 'Harare',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
            ],
        ];

        foreach($countries as $index => $country){
            Country::updateOrCreate(
                ['iso2' => $country['iso2']],
                [
                    ...$country,
                    'slug' => Str::slug($country['name']),
                    'is_active' => true,
                    'sort_order' => $index + 1,
                ]
            );
        }
    }
}